import os
import re
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

HEDGING_PHRASES = [
    "it is important to note",
    "it's worth noting",
    "in conclusion",
    "furthermore",
    "moreover",
    "additionally",
    "it is essential",
    "it is equally important",
    "in today's world",
    "plays a crucial role",
]


def llm_detect(text):
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an AI content detector. Given a piece of text, estimate the probability "
                        "that it was generated by an AI system (not written by a human). "
                        "Respond with ONLY a single decimal number between 0.0 and 1.0. "
                        "0.0 means certainly human-written, 1.0 means certainly AI-generated. "
                        "Do not include any other text."
                    ),
                },
                {"role": "user", "content": text},
            ],
            temperature=0.1,
            max_tokens=10,
        )
        score_text = response.choices[0].message.content.strip()
        score = float(score_text)
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5


def stylometric_detect(text):
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5

    words = text.split()
    total_words = len(words)
    if total_words == 0:
        return 0.5

    # Sentence length variance
    lengths = [len(s.split()) for s in sentences]
    avg_len = sum(lengths) / len(lengths)
    variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
    std_dev = variance ** 0.5
    # Low variance -> more likely AI (score higher)
    variance_score = max(0.0, 1.0 - (std_dev / 12.0))

    # Type-token ratio (lower = more repetitive = more AI-like)
    unique_words = set(w.lower() for w in words)
    ttr = len(unique_words) / total_words
    # Lower TTR -> more AI-like
    ttr_score = max(0.0, 1.0 - ttr)

    # Comma density
    comma_count = text.count(",")
    comma_per_100 = (comma_count / total_words) * 100
    # Higher comma density slightly correlates with AI
    comma_score = min(1.0, comma_per_100 / 8.0)

    # Hedging phrase count
    text_lower = text.lower()
    hedge_count = sum(1 for phrase in HEDGING_PHRASES if phrase in text_lower)
    hedge_score = min(1.0, hedge_count / 3.0)

    # Weighted average
    final = (variance_score * 0.30) + (ttr_score * 0.25) + (comma_score * 0.20) + (hedge_score * 0.25)
    return round(max(0.0, min(1.0, final)), 4)
