def compute_confidence(llm_score, stylo_score, word_count=100):
    if word_count < 50:
        final = (llm_score * 0.90) + (stylo_score * 0.10)
    else:
        final = (llm_score * 0.65) + (stylo_score * 0.35)
    return round(max(0.0, min(1.0, final)), 4)


def generate_label(score):
    if score >= 0.75:
        return {
            "label": "AI Generated (High Confidence)",
            "message": "Our system found strong indicators that this content was generated by an AI tool. This label is here to help readers understand how the content was made.",
        }
    elif score <= 0.30:
        return {
            "label": "Human Authored (High Confidence)",
            "message": "Our system found strong indicators that this content was written by a human. No AI generation signals were detected.",
        }
    else:
        return {
            "label": "Uncertain Origin",
            "message": "Our system could not determine with confidence whether this content was written by a human or generated by AI. If you believe this classification is wrong, you can submit an appeal.",
        }
